---
title: "EPIC India Small Tasks Scripts"
author: "Aarsh Batra"
date:  `r paste0("Last updated: ", Sys.Date())`
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, cache.lazy = FALSE, warning = FALSE, 
                      message =FALSE, echo = TRUE, dpi = 180, 
                      fig.width = 8, fig.height = 5)

theme_minimal()
update_geom_defaults("rect", list(fill = "midnightblue", alpha = 0.8))

```

```{r libraries}
library(tidyverse)
library(roxygen2)
library(envnames)
library(tidyr)
library(magrittr)
library(ggplot2)
library(stringr)
library(skimr)
library(purrr)
library(forcats)
library(foreign)
library(haven)
library(dplyr)
library(broom)
library(glue)
library(VIM)
library(outliers)
library(ggplot2)
library(scales)
library(grid)
library(RColorBrewer)
library(psych)
library(lubridate)
library(janitor)


```



## Task 1: Filter data for the names in the [PUC Order](https://drive.google.com/file/d/1NWQHUx85j_rCRd1qZHzHEf08FgTP-7mg/view?usp=sharing).

```{r task1-PUCOrderFilterData-read-data}
pucc_data <- read_csv("PUCC Checking by CDVs in Petrol Pumps.csv")
pucc_data <- pucc_data %>%
  clean_names()

```

```{r task1-PUCOrderFilterData-cleaning-data}


# Enter Nodal officers names list mentioned in the PUC Order PDF above
name_list <- c("nikhil", "yogesh kumar", "keshav", "dusyant yadav", 
               "saju p sharma", "kuldeep garg", "sunil kumar", 
               "yogesh", "jagdish jumar", "avinash", "angad pratab singh", 
               "rishikesh", "sunil sani", "vishal goel", "utkresh", "manish", 
               "girish chandra", "ram tirath yadav", "rajesh kumar", 
               "sagar dhiman", "guru shran mishra", "vikes solanki", 
               "mukesh kumar", "ajit singh", "robin ranjan", 
               "sunil kumar", "sachin sharan", "vishal rana", 
               "naresh", "jag mohan")

# enter date range for filtering PUC data
date_range <- lubridate::as_date(lubridate::ymd("2021-11-15") : lubridate::ymd("2021-11-19"))

# filtered_dataset
pucc_data_filtered <- pucc_data %>%
  dplyr::mutate(dateOnly = lubridate::ymd(unlist(str_extract_all(timestamp, "..../../.."))), civil_defence_volunteer_name = stringr::str_to_lower(civil_defence_volunteer_name)) %>%
  dplyr::filter(dateOnly  %in% date_range) %>%
  dplyr::filter(civil_defence_volunteer_name %in% name_list)

# save puc filtered dataset
write_csv(pucc_data_filtered, "pucc_data_filtered_nov152021Onwards_namesInPUCOrderList.csv")

```

